language: none
sudo: required

services:
  - docker

branches:
  only:
    - /.*/

before_script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD

script: docker build -t onyxpay/onyxchain-explorer-frontend:$TRAVIS_TAG .
