language: none
sudo: required

services:
  - docker

branches:
  only:
    - /.*/

before_script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD

script: docker build

deploy:
  - provider: script
    script: docker login --help ; echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_LOGIN" --password-stdin ; docker push onyxpay/onyxchain-explorer-frontend:$TRAVIS_TAG

    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^prod|preprod$
